language: node_js
node_js:
  - "8"
script: "./node_modules/.bin/ng build --prod --base-href='/enigma'"
deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
      branch: master
