language: node_js
node_js:
  - "8"
cache: yarn
script: "./node_modules/.bin/ng build --prod --aot --base-href='/enigma/' --deploy-url='/enigma/'"
deploy:
  provider: script
  skip_cleanup: true
  script: "chmod +x scripts/deploy.sh && scripts/deploy.sh"
  on:
      branch: master
